application: openshift-gce-devel 
module: github
version: 1
runtime: python27
api_version: 1
threadsafe: yes
instance_class: F2

handlers:
- url: /digest
  script: admin.app
- url: /admin.*
  script: admin.app
  login: admin
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "latest"

builtins:
- deferred: on
